services:
  db:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - pgai_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgai_data:
