// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: institution.sql

package repository

import (
	"context"
)

const insertInstitution = `-- name: InsertInstitution :one

INSERT INTO institution (id, name)
VALUES (uuid_generate_v4(), $1)
RETURNING id, name
`

func (q *Queries) InsertInstitution(ctx context.Context, name string) (Institution, error) {
	row := q.db.QueryRow(ctx, insertInstitution, name)
	var i Institution
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
