// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID       uuid.UUID `json:"id"`
	Link     string    `json:"link"`
	RecordID uuid.UUID `json:"record_id"`
}

type Institution struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Occasion struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Person struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
}

type Record struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	SpeakerID      uuid.UUID `json:"speaker_id"`
	Content        string    `json:"content"`
	Events         []byte    `json:"events"`
	SequenceNumber int32     `json:"sequence_number"`
}

type Session struct {
	ID            uuid.UUID `json:"id"`
	InstitutionID uuid.UUID `json:"institution_id"`
	OccasionID    uuid.UUID `json:"occasion_id"`
	DateTime      time.Time `json:"date_time"`
}
